// Generated by gencpp from file practica_servicios/position.msg
// DO NOT EDIT!


#ifndef PRACTICA_SERVICIOS_MESSAGE_POSITION_H
#define PRACTICA_SERVICIOS_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <practica_servicios/positionRequest.h>
#include <practica_servicios/positionResponse.h>


namespace practica_servicios
{

struct position
{

typedef positionRequest Request;
typedef positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct position
} // namespace practica_servicios


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::practica_servicios::position > {
  static const char* value()
  {
    return "67636d9847fb93c72071ab4322f7a01c";
  }

  static const char* value(const ::practica_servicios::position&) { return value(); }
};

template<>
struct DataType< ::practica_servicios::position > {
  static const char* value()
  {
    return "practica_servicios/position";
  }

  static const char* value(const ::practica_servicios::position&) { return value(); }
};


// service_traits::MD5Sum< ::practica_servicios::positionRequest> should match 
// service_traits::MD5Sum< ::practica_servicios::position > 
template<>
struct MD5Sum< ::practica_servicios::positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::practica_servicios::position >::value();
  }
  static const char* value(const ::practica_servicios::positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::practica_servicios::positionRequest> should match 
// service_traits::DataType< ::practica_servicios::position > 
template<>
struct DataType< ::practica_servicios::positionRequest>
{
  static const char* value()
  {
    return DataType< ::practica_servicios::position >::value();
  }
  static const char* value(const ::practica_servicios::positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::practica_servicios::positionResponse> should match 
// service_traits::MD5Sum< ::practica_servicios::position > 
template<>
struct MD5Sum< ::practica_servicios::positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::practica_servicios::position >::value();
  }
  static const char* value(const ::practica_servicios::positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::practica_servicios::positionResponse> should match 
// service_traits::DataType< ::practica_servicios::position > 
template<>
struct DataType< ::practica_servicios::positionResponse>
{
  static const char* value()
  {
    return DataType< ::practica_servicios::position >::value();
  }
  static const char* value(const ::practica_servicios::positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRACTICA_SERVICIOS_MESSAGE_POSITION_H
